@startuml
package "Payment Service" {
skinparam linetype ortho
skinparam ranksep 80
skinparam nodesep 150

UseCase -[hidden]l-> PaymentRequest
PaymentService -[hidden]r-> PaymentGatewayPort
PaymentPersistenceService -[hidden]d-> JpaRepository

  class Payment{
    +paymentId: UUID
    +apiKey: String
    +amount: BigDecimal
    +status: PaymentStatus
    +createdAt: LocalDateTime = LocalDateTime.now()
    +mapStatus(Integer httpStatus): PaymentStatus
  }

  enum PaymentStatus {
      SUCCESS,
      CLIENT_ERROR,
      SERVER_ERROR,
      FAILED,
      UNKNOWN_ERROR
  }

  class PaymentOutbox {
      +sagaId: UUID
      +paymentId: UUID
      +status: OutboxStatus
      +eventType: EventType
      +apiKey: String
      +amount: BigDecimal
      +createdAt: LocalDateTime = LocalDateTime.now()
  }

  enum OutboxStatus {
      PENDING,
      SENT
  }

  enum EventType {
      SUCCESS,
      FAILURE
  }

  class PaymentRequest {
    +orderId: Long
    +sagaId: UUID
    +eventType: String
    +status: OutboxStatus
    +apiKey: String
    +productDesc: String
    +amount: BigDecimal
    +amountTaxFree: Long
  }

  class PaymentPersistenceRequest {
    +sagaId: UUID
    +statusCode: Integer
    +apiKey: String
    +amount: BigDecimal
  }

  interface UseCase<I, O> {
      +execute(input: I): O
  }

  interface PaymentUseCase {
      +execute(input: PaymentRequest): Void
  }

  interface PaymentPersistenceUseCase {
      +execute(input: PaymentPersistenceRequest): Void
  }

  class PaymentMessageListener {
    - paymentUseCase: PaymentUseCase
    +onMessage(input: PaymentRequest): Void
  }

  class PaymentService {
    - paymentPersistenceUseCase: PaymentPersistenceUseCase
    - paymentGatewayPort: PaymentGatewayPort
    +execute(input: PaymentRequest): Void
  }

  class PaymentPersistenceService {
    - paymentRepository: PaymentRepository
    - paymentOutboxRepository: PaymentOutboxRepository
    +execute(input: PaymentPersistenceRequest): Void
  }

  interface PaymentGatewayPort {
    +pay()
    +refund()
  }

  interface PaymentRepository {
    +save(paymentEntity: Payment)
    +findById(paymentId: UUID): Optional<Payment>
  }

  interface PaymentOutboxRepository {
    +save(outboxEntity: PaymentOutbox)
  }

  class PGAdapter {
    - externalPG: ExternalPG
    +pay()
    +refund()
  }

  class ExternalPG {
    +pay()
    +refund()
  }

  interface JpaRepository {
  }

  JpaRepository <|-- PaymentRepository
  JpaRepository <|-- PaymentOutboxRepository

  Payment "1" -- "1" PaymentOutbox
  Payment --> PaymentStatus
  PaymentOutbox --> OutboxStatus
  PaymentOutbox --> EventType
  PaymentRequest --> OutboxStatus

  PaymentMessageListener --> PaymentUseCase

  PaymentUseCase -up-|> UseCase
  PaymentPersistenceUseCase -up-|> UseCase

  PaymentUseCase <|.. PaymentService
  PaymentPersistenceUseCase <|.. PaymentPersistenceService

  PaymentService --> PaymentPersistenceUseCase
  PaymentService --> PaymentGatewayPort
  PGAdapter ..|> PaymentGatewayPort
  PGAdapter --> ExternalPG

  PaymentPersistenceService --> PaymentRepository
  PaymentPersistenceService --> PaymentOutboxRepository
}
@enduml