@startuml
skinparam linetype ortho
top to bottom direction

skinparam ranksep 150
skinparam nodesep 250

object "PaymentMessageListener" as listener
object "PaymentService" as service
object "Redis\n(IdempotencyStore)" as redis
object "MockService" as mockService
object "PaymentPersistenceService" as persistence
object "PaymentOutboxWorker" as outboxWorker
object "MessageBroker\n(RabbitMQ)" as broker
package "Same Transaction" as dbtx {
  object "PaymentRepository" as paymentRepo
  object "PaymentOutboxRepository" as outboxRepo
}

listener -[hidden]down-> service

service -[hidden]right-> mockService

service  -[hidden]down-> persistence
persistence -[hidden]down-> outboxWorker
outboxWorker -[hidden]down-> broker

persistence -[hidden]down-> paymentRepo
persistence -[hidden]down-> outboxRepo
paymentRepo -[hidden]right-> outboxRepo

listener -down-> service : 1: 결제 요청 메시지 수신(onMessage)

service -left-> redis  : 1.0.1: idempotency key 조회 요청
redis   -right-> service : 1.0.2: idempotency 조회 결과 반환
service -up-> listener  : 1.0.3: 기처리된 요청 결과 반환

note right of service
1.0.2 결과가 "이미 처리"인 경우 →
  1.0.3 응답 반환 후 종료
1.0.2 결과가 "미처리"인 경우 →
  1.1부터 신규 결제 처리 계속
end note

service -right-> mockService : 1.1: 결제 요청 전송
mockService -left-> service  : 1.2: 결제 결과 반환

service -down-> persistence : 2: 결제 정보 저장 요청

persistence -down-> paymentRepo : 2.1.1: 결제 엔티티 저장
persistence -down-> outboxRepo  : 2.1.2: Outbox 이벤트 저장

note right of persistence
2.1.1, 2.1.2는
동일 트랜잭션에서
원자적으로 저장됨
end note

outboxWorker -up-> outboxRepo : 3: 처리되지 않은 Outbox 조회
outboxRepo   -down-> outboxWorker : 4: 조회 결과 반환

outboxWorker -down-> broker : 5: Payment 이벤트 발행
broker       -up-> outboxWorker : 6: ACK 응답

outboxWorker -up-> outboxRepo : 7: Outbox 상태 COMPLETED로 업데이트

@enduml
