@startuml
autonumber
skinparam linetype ortho

database "PostgreSQL DB" as SourceDB
participant "Debezium (Connector)" as Debezium

participant "DebeziumMessageListener" as Listener
participant "WorkerService" as WorkerService
participant "RabbitMqPublisher" as Publisher
participant "RabbitTemplate" as RabbitTemplate
participant "RabbitMQ" as RabbitMQ
participant "OrderPersistenceService" as PersistenceService
database "OrderOutboxRepository" as OutboxRepo

== Debezium Event Consume ==
Debezium -> SourceDB : read WAL
note right of SourceDB
WAL (Write-Ahead Log)
PostgreSQL transaction log
used for CDC
end note

Debezium -> Listener : change event

Listener -> Listener : parse payload\nmap OrderOutboxRecord

alt status == SENT
  Listener -> Listener : ignore
else status != SENT
  Listener -> WorkerService : execute(workerRequest)

  == Publish (sync) ==
  WorkerService -> Publisher : publish(workerRequest)
  Publisher -> RabbitTemplate : convertAndSend(...)

  RabbitTemplate -> RabbitMQ : publish(message)
end

== Publisher Confirm (async) ==

RabbitMQ ->> RabbitTemplate : ack(correlationData)

RabbitTemplate -> PersistenceService : updateStatus(correlationData.id)

PersistenceService -> OutboxRepo : findBySagaId(id)
OutboxRepo --> PersistenceService : OrderOutboxEntity

PersistenceService -> OutboxRepo : save(status = SENT)
OutboxRepo --> PersistenceService : saved entity

@enduml
